### PR TITLE
Change PDF font from 10px to 11px

### PR DESCRIPTION
**Pull request by martaribeiro**
Fixes #193 
https://github.com/DigitalCurationCentre/DMPonline-Service/issues/193

Changes proposed in this PR:
- It should replace the default 10px to 11px when exporting a pdf.

### CODE REVIEW

**Comment by raycarrick-ed** [comment]
There are a number of problems here:

1. why is this being PR'd to deploy/dmponline? if it's a global change should it also apply to roadmap? if not then I'd have expected it to be a customisation within the docker environment so that we can pull in a new roadmap codebase and it'll still work.
2. Putting raw numbers in code is really bad practice. Especially weird ones like that.
3. the original code uses a font_size variable. Why can't that be set properly somewhere. That would seem like a better approach.

This just looks like the wrong way to do this.

**Comment by raycarrick-ed** [comment]
also should it not be 11pt not 11px?

**Comment by raycarrick-ed** [comment]
or, again, if it's a change for the installation then why not make the change in a config file like _dmproadmap.rb?

**Comment by pherterich** [comment]
@martaribeiro - once you are done with accessibility tickets, you might want to address this code review

**Pull request closed without merging**
